[build-system]
requires = [
  "setuptools >= 40.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "haposctl-webui"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.12"',
]
